### ISSUE TITLE
Missing product_categories Details and Handling Null Category

### ISSUE THREAD

**Issue by bagusgandhi** [FarhanKurnia/habbie#1]
I found an issue in the ClientController file at the indexProductsByCat method. The details of the product_categories are not being returned to the view. Additionally, if a category does not have any products yet, it throws an **ErrorException** with the message **Attempt to read property 'category' on null** because the view is trying to access the category name from the product data.

To resolve this issue, could you please return the details of the product_categories as well, including fields such as name, slug, and id_category?

**Comment by FarhanKurnia** [comment]
for now I'm adding category in indexProductByCat for title depends on the categories so you can consume property 'category'. I also updated the example in test view.
